### ISSUE TITLE
error building pyenchant 1.6.6 on OS X 10.11.5

### ISSUE THREAD

**Issue by tkimnguyen** [plone/papyrus#102]
I was following the instructions at https://github.com/plone/papyrus/blob/5.0/docs/install.rst and got this when I ran bin/buildout:

```
bin/buildout 
mr.developer: Creating missing sources dir /Users/kim/src/papyrus/checkouts.
mr.developer: Queued 'ansible-playbook' for checkout.
mr.developer: Queued 'bobtemplates.plone' for checkout.
mr.developer: Queued 'buildout.coredev' for checkout.
mr.developer: Queued 'collective.transmogrifier' for checkout.
mr.developer: Queued 'diazo' for checkout.
mr.developer: Queued 'documentation' for checkout.
mr.developer: Queued 'plone.api' for checkout.
mr.developer: Queued 'plone.app.caching' for checkout.
mr.developer: Queued 'plone.app.contentlisting' for checkout.
mr.developer: Queued 'plone.app.contenttypes' for checkout.
mr.developer: Queued 'plone.app.dexterity' for checkout.
mr.developer: Queued 'plone.app.event' for checkout.
mr.developer: Queued 'plone.app.multilingual' for checkout.
mr.developer: Queued 'plone.app.robotframework' for checkout.
mr.developer: Queued 'plone.app.testing' for checkout.
mr.developer: Queued 'plone.app.theming' for checkout.
mr.developer: Queued 'plone.testing' for checkout.
mr.developer: Queued 'sphinx-intl' for checkout.
mr.developer: Queued 'sphinx.themes.plone' for checkout.
mr.developer: Queued 'sphinxcontrib-osexample' for checkout.
mr.developer: Cloned 'ansible-playbook' with git.
mr.developer: Cloned 'collective.transmogrifier' with git.
mr.developer: Cloned 'diazo' with git.
mr.developer: Cloned 'bobtemplates.plone' with git.
mr.developer: Cloned 'buildout.coredev' with git.
mr.developer: Cloned 'plone.app.contentlisting' with git.
mr.developer: Cloned 'plone.app.caching' with git.
mr.developer: Cloned 'plone.app.contenttypes' with git.
mr.developer: Cloned 'plone.api' with git.
mr.developer: Cloned 'plone.app.event' with git.
mr.developer: Cloned 'plone.app.dexterity' with git.
mr.developer: Cloned 'plone.app.robotframework' with git.
mr.developer: Cloned 'plone.app.testing' with git.
mr.developer: Cloned 'plone.app.multilingual' with git.
mr.developer: Cloned 'plone.testing' with git.
mr.developer: Cloned 'sphinx-intl' with git.
mr.developer: Cloned 'plone.app.theming' with git.
mr.developer: Cloned 'sphinxcontrib-osexample' with git.
mr.developer: Cloned 'sphinx.themes.plone' with git.
mr.developer: Cloned 'documentation' with git.
---------------------------------------------------------
The current global buildout threat level is: [42m  [37mLOW[39m  [49m
---------------------------------------------------------
Develop: '/Users/kim/src/papyrus/checkouts/sphinx-intl'
Develop: '/Users/kim/src/papyrus/checkouts/sphinxcontrib-osexample'
warning: no files found matching 'LICENSE'
no previously-included directories found matching 'docs'
no previously-included directories found matching 'lexer'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'requirements.txt'
Develop: '/Users/kim/src/papyrus/checkouts/sphinx.themes.plone'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Getting distribution for 'collective.recipe.template[genshi]==1.13'.
Got collective.recipe.template 1.13.
Getting distribution for 'Genshi'.
warning: no previously-included files matching '*' found under directory 'doc/logo.lineform'
warning: no previously-included files found matching 'doc/2000ft.graffle'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got Genshi 0.7.
Getting distribution for 'plone.recipe.command'.
Got plone.recipe.command 1.1.
Installing _mr.developer.
Generated script '/Users/kim/src/papyrus/bin/develop'.
Installing assembly-script.
Installing assemble-docs.
assemble-docs: Running '/Users/kim/src/papyrus/bin/assemble-docs.sh'
Assemble documentation from its several sources...
- documentation symlinked at /Users/kim/src/papyrus/source/documentation
- bobtemplates.plone is turned into a sparse checkout
- bobtemplates.plone symlinked at /Users/kim/src/papyrus/source/documentation/develop/addons/bobtemplates.plone
- buildout.coredev is turned into a sparse checkout
- buildout.coredev symlinked at /Users/kim/src/papyrus/source/documentation/develop/coredev
- ansible-playbook is turned into a sparse checkout
- ansible-playbook symlinked at /Users/kim/src/papyrus/source/documentation/external/ansible-playbook
- collective.transmogrifier is turned into a sparse checkout
- collective.transmogrifier symlinked at /Users/kim/src/papyrus/source/documentation/external/collective.transmogrifier
- diazo is turned into a sparse checkout
- diazo symlinked at /Users/kim/src/papyrus/source/documentation/external/diazo
- plone.api is turned into a sparse checkout
- plone.api symlinked at /Users/kim/src/papyrus/source/documentation/develop/plone.api
- plone.app.caching is turned into a sparse checkout
- plone.app.caching symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.caching
- plone.app.contentlisting is turned into a sparse checkout
- plone.app.contentlisting symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.contentlisting
- plone.app.contenttypes is turned into a sparse checkout
- plone.app.contenttypes symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.contenttypes
- plone.app.dexterity is turned into a sparse checkout
- plone.app.dexterity symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.dexterity
- plone.app.event is turned into a sparse checkout
- plone.app.event symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.event
- plone.app.multilingual is turned into a sparse checkout
- plone.app.multilingual symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.multilingual
- plone.app.robotframework is turned into a sparse checkout
- plone.app.robotframework symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.robotframework
- plone.app.testing is turned into a sparse checkout
- plone.app.testing symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.testing
- plone.app.theming is turned into a sparse checkout
- plone.app.theming symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.app.theming
- plone.testing is turned into a sparse checkout
- plone.testing symlinked at /Users/kim/src/papyrus/source/documentation/external/plone.testing
... done
Unused options for assemble-docs: 'update-command'.
Installing sphinx-build.
Getting distribution for 'Plone==5.0.4'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

Got Plone 5.0.4.
Getting distribution for 'Sphinx==1.3.6'.
warning: no files found matching 'TODO'
no previously-included directories found matching 'doc/_build'
Got Sphinx 1.3.6.
Getting distribution for 'sphinxcontrib-robotframework[docs]==0.5.1'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got sphinxcontrib-robotframework 0.5.1.
Getting distribution for 'plone.app.robotframework[speak]==0.9.14'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got plone.app.robotframework 0.9.14.
Getting distribution for 'pyenchant'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2279, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1065, in run_setup
    run_setup(setup_script, args)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/Users/kim/src/papyrus/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/var/folders/jj/9058xkld5rz8rk21d_s299xc0000gp/T/easy_install-6wRxa8/pyenchant-1.6.6/setup.py", line 210, in <module>

  File "/var/folders/jj/9058xkld5rz8rk21d_s299xc0000gp/T/easy_install-6wRxa8/pyenchant-1.6.6/enchant/__init__.py", line 92, in <module>
  File "/var/folders/jj/9058xkld5rz8rk21d_s299xc0000gp/T/easy_install-6wRxa8/pyenchant-1.6.6/enchant/_enchant.py", line 143, in <module>
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
An error occurred when trying to install pyenchant 1.6.6. Look above this message for any errors that were output by easy_install.
While:
  Installing sphinx-build.
  Getting distribution for 'pyenchant'.
Error: Couldn't install: pyenchant 1.6.6
(papyrus)bash-3.2$ 
```

I take it this means I should install from http://pythonhosted.org/pyenchant/download.html ? Ah no it seems "Mac OSX users can also follow the instructions above to build from source, after installing the underlying enchant library via e.g. macports or homebrew."

**Comment by tkimnguyen** [comment]
Yes, "brew install enchant" was all that was needed. Is it worth changing https://github.com/plone/papyrus/blob/5.0/docs/install.rst to reflect this as a requirement for OS X?

**Comment by svx** [comment]
I am not sure, this also will mean we have to update the whole installation docs, only adding 'brew install' will not work :)

Currently the docs are clearly saying: 

> To install Papyrus with all features and possibilities on Ubuntu 14.04 you will need:

I am not against it, if someone steps up and says, "Yeah I want to do that" awesome please go do so !!! :), but if so,  there should be clearly added, that people would need Homebrew, in order to follow the docs on a Mac. Not every developer on a Mac is using that.

Please keep in mind that we started re-writing papyrus, so at least me in person want to spend less time as possible on the old version, sure serious bugs, I will do that, but not for update the docs on how to install papyrus on various OS' s :).

Also as I said before, there is really no need for people to install/setup papyrus locally, we have these days editor plugins and mr.docs :)

**Comment by tkimnguyen** [comment]
I guess it's fine to have recorded the issue and the solution here.
