### ISSUE TITLE
ImportError: cannot import name _error_start

### ISSUE THREAD

**Issue by macagua** [plone/papyrus#21]
Hi @datakurre 

I am trying to update the plone.pot file for extract the new msgids and shows me this error:

```
make babel
bin/pybabel extract source/documentation -o source/documentation/_locales/pot/plone.pot
Traceback (most recent call last):
  File "bin/pybabel", line 243, in <module>
    import plone.app.robotframework.robotentrypoints
  File "/home/macagua/.buildout/eggs/plone.app.robotframework-0.9.4-py2.7.egg/plone/app/robotframework/__init__.py", line 12, in <module>
    from plone.app.robotframework.autologin import AutoLogin
  File "/home/macagua/.buildout/eggs/plone.app.robotframework-0.9.4-py2.7.egg/plone/app/robotframework/autologin.py", line 2, in <module>
    from Products.PlonePAS.Extensions.Install import activatePluginInterfaces
  File "/home/macagua/.buildout/eggs/Products.PlonePAS-5.0-py2.7.egg/Products/PlonePAS/__init__.py", line 2, in <module>
    from Products.CMFCore.utils import ToolInit
  File "/home/macagua/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/__init__.py", line 17, in <module>
    import ActionsTool, UndoTool, RegistrationTool, SkinsTool
  File "/home/macagua/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/SkinsTool.py", line 27, in <module>
    from Products.PageTemplates.ZopePageTemplate import ZopePageTemplate
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/ZopePageTemplate.py", line 42, in <module>
    from Products.PageTemplates.PageTemplate import PageTemplate
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 19, in <module>
    from zope.pagetemplate.pagetemplate import _error_start, PTRuntimeError
ImportError: cannot import name _error_start
make: *** [babel] Error 1
```

Any idea?

**Comment by svx** [comment]
closing this now, feel free to re-open :)
